import type { MediaRule, MediaStatus, MediaType } from '../types';

export const MEDIA_TYPE_OPTIONS: Array<{ title: string; value: MediaType }> = [
  { title: 'Outdoor', value: 'outdoor' },
  { title: 'Painel Iluminado - Front Light', value: 'front light' },
  { title: 'Painel Iluminado - Triface', value: 'triface' },
  { title: 'Empena', value: 'empena' },
  { title: 'Painel Eletrônico Modular', value: 'painel eletronico modular' },
  { title: 'Painel Eletrônico Modular - Pequeno Porte', value: 'painel de led' },
  { title: 'Empena Eletrônica', value: 'empena de led' },
];

export function mediaTypeOptionsFromRules(rules: MediaRule[]): Array<{ title: string; value: MediaType }> {
  if (rules.length === 0) return MEDIA_TYPE_OPTIONS;

  const activeRules = new Map(
    rules
      .filter((rule) => rule.is_active)
      .map((rule) => [rule.media_type, rule]),
  );

  return MEDIA_TYPE_OPTIONS
    .filter((option) => activeRules.has(option.value))
    .map((option) => ({
      title: activeRules.get(option.value)?.name.trim() || option.title,
      value: option.value,
    }));
}

export const STATUS_OPTIONS: Array<{ title: string; value: MediaStatus }> = [
  { title: 'Aprovado', value: 'aprovado' },
  { title: 'Irregular', value: 'irregular' },
  { title: 'Análise', value: 'análise' },
  { title: 'Exigência', value: 'exigência' },
  { title: 'Vencido', value: 'vencido' },
  { title: 'Cartografia', value: 'cartografia' },
  { title: 'Jurídico', value: 'jurídico' },
  { title: 'Vistoria', value: 'vistoria' },
];

export const DISTRICT_OPTIONS = [
  'Água Limpa Park',
  'Alphaville Campo Grande',
  'Alphaville Campo Grande 3',
  'Alphaville Campo Grande 4',
  'Alves Pereira',
  'Amambaí',
  'Amantini Residence',
  'Área Rural de Campo Grande',
  'Arnaldino da Silva',
  'Arnaldo Estevão Figueiredo',
  'Ary Abussafi de Lima',
  'Bairro Industrial',
  'Bairro São Pedro',
  'Bairro Seminário',
  'Barra da Tijuca II',
  'Beirute Residence Park',
  'Bom Retiro',
  'Bonjardim',
  'Bosque das Araras',
  'Bosque de Avilan',
  'Bosque do Carvalho',
  'Bosque Santa Mônica',
  'Bosque Santa Mônica II',
  'Cabreúva',
  'Caiçara',
  'Caiobá',
  'Campo Dourado',
  'Carandá Bosque',
  'Centenário',
  'Center Park',
  'Centro',
  'Centro Oeste',
  'Chácara Cachoeira',
  'Chácara das Mansões',
  'Chácara dos Poderes',
  'Chácara Lageado',
  'Chácara Santa Abadia',
  'Cidade Jardim',
  'Cohafama',
  'Colinas de Campo Grande',
  'Conjunto Aero Rancho',
  'Conjunto Habitacional Estrela D’Alva I',
  'Conjunto Habitacional Estrela D’Alva II',
  'Conjunto Habitacional Estrela D’Alva III',
  'Conjunto Habitacional Jardim Talismã',
  'Conjunto Habitacional Nascente Segredo',
  'Conjunto Iracy Coelho III',
  'Conjunto José Abrão',
  'Conjunto Parati II',
  'Conjunto Residencial Botafogo',
  'Conjunto Residencial Estrela do Sul',
  'Conjunto Residencial Nova Olinda',
  'Conjunto Residencial Octavio Pécora',
  'Conjunto Residencial Recanto dos Rouxinóis',
  'Conjunto União II',
  'Coophafé',
  'Coophamat',
  'Coopharádio',
  'Coophasul',
  'Coophatrabalho',
  'Coophavila II',
  'Coronel Antonino',
  'Delfos Residencial',
  'Dom Antônio Barbosa',
  'Edson Brito Garcia',
  'Gregorio Correa',
  'Guanandi',
  'Guanandi II',
  'Indaiá Park',
  'Itanhangá Park',
  'Jardim Aero Rancho',
  'Jardim Aeroporto',
  'Jardim Agulhas Negras',
  'Jardim Alto São Francisco',
  'Jardim América',
  'Jardim Anache',
  'Jardim Anápolis I',
  'Jardim Antáres',
  'Jardim Arco-Íris',
  'Jardim Autonomista',
  'Jardim Auxiliadora',
  'Jardim Bálsamo',
  'Jardim Barcelona',
  'Jardim Batistão',
  'Jardim Bela Vista',
  'Jardim Bonança',
  'Jardim Botânico',
  'Jardim Botânico II',
  'Jardim Campina Verde',
  'Jardim Campo Alto',
  'Jardim Campo Belo',
  'Jardim Campo Nobre',
  'Jardim Campo Verde',
  'Jardim Canguru',
  'Jardim Carioca',
  'Jardim Centenário',
  'Jardim Centro Oeste',
  'Jardim Colibrí',
  'Jardim Colibri II',
  'Jardim Colonial',
  'Jardim Colorado',
  'Jardim Colúmbia',
  'Jardim Corcovado',
  'Jardim da Mooca',
  'Jardim das Cerejeiras',
  'Jardim das Hortências',
  'Jardim das Macaúbas',
  'Jardim das Meninas',
  'Jardim das Nações',
  'Jardim das Perdizes',
  'Jardim das Reginas',
  'Jardim das Virtudes',
  'Jardim do Córrego',
  'Jardim do Zé Pereira',
  'Jardim dos Estados',
  'Jardim Enseada dos Pássaros',
  'Jardim Fluminense',
  'Jardim Imá',
  'Jardim Inápolis',
  'Jardim Indianápolis',
  'Jardim Itália',
  'Jardim Itamaracá',
  'Jardim Itapuã',
  'Jardim Itatiaia',
  'Jardim Jacy',
  'Jardim Jatobá',
  'Jardim Jerusalém',
  'Jardim Jockey Club',
  'Jardim Leblon',
  'Jardim Los Angeles',
  'Jardim Macapá',
  'Jardim Manaíra',
  'Jardim Mansur',
  'Jardim Mathilde',
  'Jardim Moema',
  'Jardim Monte Alegre',
  'Jardim Monte Líbano',
  'Jardim Monterey',
  'Jardim Montevidéu',
  'Jardim Monumento',
  'Jardim Morenão',
  'Jardim Nashville',
  'Jardim Nhanhá',
  'Jardim Noroeste',
  'Jardim Nossa Senhora do Perpétuo Socorro',
  'Jardim Nova Era',
  'Jardim Nova Jerusalém',
  'Jardim Ouro Preto',
  'Jardim Pacaembu',
  'Jardim Paradiso',
  'Jardim Parati',
  'Jardim Paulista',
  'Jardim Paulo Coelho Machado',
  'Jardim Pênfigo',
  'Jardim Petrópolis',
  'Jardim Presidente',
  'Jardim Radialista',
  'Jardim Samambaia',
  'Jardim Santa Emília',
  'Jardim Santa Felicidade',
  'Jardim São Bento',
  'Jardim São Conrado',
  'Jardim São Lourenço',
  'Jardim Sarandí',
  'Jardim Sayonara',
  'Jardim Sumatra',
  'Jardim Tarumã',
  'Jardim Tijuca',
  'Jardim Tropical',
  'Jardim TV Morena',
  'Jardim Uirapuru',
  'Jardim Veraneio',
  'Jardim Vida Nova',
  'Jardim Vida Nova II',
  'José Maksoud',
  'José Tavares do Couto',
  'Lagoa da Cruz',
  'Lagoa Dourada',
  'Lagoa Park',
  'Lagoa Rica',
  'Lar do Trabalhador',
  'Loteamento Alto da Boa Vista',
  'Loteamento Bosque da Esperança',
  'Loteamento Costa Verde',
  'Loteamento Cristo Redentor',
  'Loteamento Dona Dedé',
  'Loteamento José Prates',
  'Loteamento Marçal de Souza',
  'Loteamento Papa João Paulo II',
  'Loteamento Paulo VI',
  'Loteamento Portobello',
  'Loteamento Praia da Urca',
  'Loteamento Rancho Alegre II',
  'Loteamento Tarcila do Amaral',
  'Loteamento Vespasiano Martins',
  'Maria Aparecida Pedrossian',
  'Mata do Jacinto',
  'Mata do Segredo',
  'Monte Carlo',
  'Monte Castelo',
  'Morada do Sol',
  'Morada do Sossego',
  'Morada do Sossego II',
  'Morada dos Deuses',
  'Morada Verde',
  'Moreninha',
  'North Park',
  'Nova Lima',
  'Nova Serrana',
  'Núcleo Habitacional Buriti',
  'Núcleo Habitacional Universitárias',
  'Núcleo Industrial',
  'Oscar Salazar Moura da Cruz',
  'Panamá',
  'Panorama',
  'Parque Atlântico',
  'Parque Dallas',
  'Parque do Lageado',
  'Parque do Sol',
  'Parque dos Laranjais',
  'Parque dos Novos Estados',
  'Parque dos Poderes',
  'Parque dos Sabiás',
  'Parque Fazenda Imbirussu',
  'Parque Iguatemi',
  'Parque Isabel Gardens',
  'Parque Novo Século',
  'Parque Residencial Azaléia',
  'Parque Residencial dos Girassóis',
  'Parque Residencial Iracy Coelho Netto',
  'Parque Residencial Rita Vieira',
  'Parque Residencial União',
  'Pioneiros',
  'Polo Empresarial',
  'Polo Empresarial Oeste',
  'Portal Caiobá',
  'Portal Caiobá II',
  'Portal do Panamá',
  'Portal Itayara',
  'Porto Galo',
  'Rancho Alegre I',
  'Rancho Alegre III',
  'Rancho Alegre IV',
  'Recanto das Paineiras',
  'Recanto do Cerrado',
  'Recanto dos Pássaros',
  'Recanto Pantaneiro',
  'Residencial Nelson Trad',
  'Residencial Alto Tamandaré',
  'Residencial Ana Maria do Couto',
  'Residencial Aquários I',
  'Residencial Aquários II',
  'Residencial Atlântico Sul',
  'Residencial Betaville',
  'Residencial Búzios',
  'Residencial Carajás',
  'Residencial Cedrinho',
  'Residencial Damha',
  'Residencial Damha II',
  'Residencial Damha III',
  'Residencial Estrela Park',
  'Residencial Flores',
  'Residencial Gabura',
  'Residencial Gama',
  'Residencial Hugo Rodrigues',
  'Residencial Ilhéus',
  'Residencial Joana D’Arc',
  'Residencial João Alberto A. dos Santos',
  'Residencial José Teruel Filho',
  'Residencial Mário Covas',
  'Residencial Oiti',
  'Residencial Oliveira',
  'Residencial Oliveira III',
  'Residencial Pequena Flor',
  'Residencial Ramez Tebet',
  'Residencial Sírio-Libanês I',
  'Residencial Sírio-Libanês II',
  'Residencial Sóter',
  'Residencial Terra dos Pequis',
  'Residencial Terra Morena',
  'Residencial Via Park Itália',
  'Residencial Vida Nova III',
  'Residencial Vila Bela',
  'Residencial Villa Lobos',
  'Rita Vieira',
  'Rivieira Park',
  'Royal Park',
  'Santa Fé',
  'Santo Amaro',
  'Santo Antônio',
  'São Francisco',
  'Serraville',
  'Setvillage I',
  'Setvillage II',
  'Sobrinho',
  'Taquaral Bosque',
  'Tayamã Park',
  'Terras Alpha Campo Grande',
  'Tiradentes',
  'Trevisso',
  'Universitário',
  'Universitário Seção D',
  'Varanda do Campo',
  'Vila Adelina',
  'Vila Aimoré',
  'Vila Alba',
  'Vila Albuquerque',
  'Vila Almeida',
  'Vila Amapá',
  'Vila Anahy',
  'Vila Antônio Vendas',
  'Vila Antunes',
  'Vila Bandeirante',
  'Vila Base Aérea',
  'Vila Belo Horizonte',
  'Vila Bordon',
  'Vila Carlota',
  'Vila Carvalho',
  'Vila Célia',
  'Vila Cidade Morena',
  'Vila Clélia',
  'Vila Concórdia',
  'Vila Danúbio Azul',
  'Vila do Polonês',
  'Vila Duque de Caxias',
  'Vila Eliane',
  'Vila Entroncamento',
  'Vila Fernanda',
  'Vila Flório',
  'Vila Futurista',
  'Vila Giocondo Orsi',
  'Vila Glória',
  'Vila Gomes',
  'Vila Ieda',
  'Vila Ipiranga',
  'Vila Jardim Botafogo',
  'Vila Joselito',
  'Vila Julieta',
  'Vila Jussara',
  'Vila Maciel',
  'Vila Manoel da Costa Lima',
  'Vila Manoel Sêcco Thomé',
  'Vila Manoel Taveira',
  'Vila Marcos Roberto',
  'Vila Margarida',
  'Vila Marli',
  'Vila Matel',
  'Vila Miguel Couto',
  'Vila Moreninha I',
  'Vila Moreninha II',
  'Vila Moreninha III',
  'Vila Moreninha IV',
  'Vila Morumbi',
  'Vila Nascente',
  'Vila Nasser',
  'Vila Nathália',
  'Vila Neusa',
  'Vila Nogueira',
  'Vila Nossa Senhora das Graças',
  'Vila Nova Campo Grande',
  'Vila Nova Capital',
  'Vila Oeste',
  'Vila Olinda',
  'Vila Orfeu Baís',
  'Vila Palmira',
  'Vila Piratininga',
  'Vila Planalto',
  'Vila Popular',
  'Vila Progresso',
  'Vila Ravenna',
  'Vila Rica',
  'Vila Romana',
  'Vila Rosa Pires',
  'Vila Santa Dorothéia',
  'Vila Santa Luzia',
  'Vila Santo Amaro',
  'Vila Santo Eugênio',
  'Vila Santos Gomes',
  'Vila São Jorge da Lagoa',
  'Vila São Vicente',
  'Vila Sargento Amaral',
  'Vila Serradinho',
  'Vila Sílvia Regina',
  'Vila Taquarussu',
  'Vila Taveirópolis',
  'Vila Vilas Boas',
  'Vila Volpe',
  'Vila Volpe II',
  'Vivendas do Bosque',
  'Vivendas do Parque',
]

export function getRequiredRadius(mediaType: MediaType, areaM2: number, rules: MediaRule[] = []): number {
  const managedRule = rules.find((rule) => rule.media_type === mediaType && rule.is_active);
  if (managedRule) {
    if (
      managedRule.area_threshold_m2 != null
      && managedRule.radius_above_threshold_meters != null
      && areaM2 > managedRule.area_threshold_m2
    ) {
      return managedRule.radius_above_threshold_meters;
    }
    return managedRule.base_radius_meters;
  }
  if (mediaType === 'painel de led') return areaM2 > 5 ? 1000 : 250;
  if (mediaType === 'painel eletronico modular' || mediaType === 'empena de led') return 1000;
  return 80;
}

export function mediaTypeLabel(mediaType: MediaType): string {
  return MEDIA_TYPE_OPTIONS.find((item) => item.value === mediaType)?.title ?? mediaType;
}

export function mediaTypeColor(mediaType: MediaType): string {
  const colors: Record<MediaType, string> = {
    outdoor: '#2f80ed',
    'front light': '#219653',
    triface: '#7b61ff',
    'painel de led': '#f2994a',
    'painel eletronico modular': '#ef6c00',
    empena: '#d9468f',
    'empena de led': '#0e9f9a',
  };
  return colors[mediaType];
}

export function statusColor(status: MediaStatus): string {
  if (status === 'aprovado') return 'success';
  if (status === 'irregular' || status === 'vencido') return 'error';
  if (status === 'cartografia' || status === 'jurídico') return 'primary';
  return 'warning';
}

export function statusLabel(status: MediaStatus): string {
  return STATUS_OPTIONS.find((item) => item.value === status)?.title ?? status;
}
